# Generated by Django 5.1 on 2024-08-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_auth_package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpasswordmodel',
            name='otp_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
